/**
 * GameState.ts
 * Global mutable state singleton — replaces AS3 global variable scope.
 * All game modules import `gs` and read/write properties on it.
 */

export const gs = {
  // ── Version ───────────────────────────────────
  versionNumber: '0.975o',

  // ── Personalization ───────────────────────────
  theme: 0,
  fontSize: 14,
  fontBold: false,
  fontColor: 'cccccc',
  showSide: true,

  // ── General runtime vars ──────────────────────
  i: 0,
  buttonChoice: 0,
  currentText: '',
  sideText: '',
  sideFocus: 1,
  pregTempInt: 0,
  pregTempBool: false,
  lustArray: [] as any[],
  rndResult: 0,
  rndArray: [] as number[],
  textCheckArray: [] as any[],
  choiceListArray: [] as any[],
  choiceListResult: [] as any[],
  choicePage: 1,
  moveItemID: 0,
  moveItemStack: 0,
  skipExhaustion: false,
  shiftHeld: false,

  // ── Navigation state ──────────────────────────
  currentState: 0,   // 0=menu, 1=general, 2=battle, 3=masturbate
  inBag: false,
  inShop: false,
  currentZone: 0,
  inDungeon: false,
  currentDungeon: 0,

  // ── Time ──────────────────────────────────────
  day: 0,
  hour: 8,

  // ── Visible stats ─────────────────────────────
  str: 0,
  ment: 0,
  lib: 0,
  sen: 0,
  HP: 0,
  lust: 0,
  coin: 0,
  strMod: 0,
  mentMod: 0,
  libMod: 0,
  senMod: 0,
  strength: 0,
  mentality: 0,
  libido: 0,
  sensitivity: 0,
  hunger: 0,

  // ── Utility vars ──────────────────────────────
  hrs: 0,
  itemGainArray: [] as number[],
  human: 0,
  horse: 0,
  wolf: 0,
  cat: 0,
  cow: 0,
  lizard: 0,
  rabbit: 0,
  mouse: 0,
  bird: 0,
  pig: 0,
  skunk: 0,
  bug: 0,

  // ── Leveling ──────────────────────────────────
  SexP: 0,
  levelUP: 0,
  level: 0,

  // ── Modifying variables ───────────────────────
  runMod: 0,
  rapeMod: 0,
  cumMod: 1,
  cockSizeMod: 1,
  vagSizeMod: 1,
  vagElastic: 1,
  milkMod: 0,
  carryMod: 0,
  vagBellyMod: 0,
  pregChanceMod: 0,
  extraPregChance: 0,
  pregTimeMod: 0,
  enticeMod: 0,
  milkHPMod: 0,
  changeMod: 1,
  HPMod: 0,
  SexPMod: 1,
  minLust: 0,
  milkCap: 0,
  coinMod: 0,
  hipMod: 1,
  buttMod: 1,
  bellyMod: 0,
  cockMoistMod: 0,
  vagMoistMod: 0,
  lockTail: 0,
  lockFace: 0,
  lockSkin: 0,
  lockBreasts: 0,
  lockEars: 0,
  lockLegs: 0,
  lockNipples: 0,
  lockCock: 0,
  breastSizeMod: 1,
  nippleSizeMod: 1,
  nipNarrowMod: 1.07,
  cockNarrowMod: 1.3,
  clitNarrowMod: 1.5,
  ballSizeMod: 1,

  // ── Enemy stats ───────────────────────────────
  enemyID: 0,
  eHP: 0,
  eMaxHP: 0,
  eStr: 0,
  eMenta: 0,
  eSen: 0,
  eLib: 0,
  eLust: 0,
  eGen: 0,
  ePref: 0,
  eCoin: 0,
  eSexP: 0,
  eItem: 0,

  // ── Body / appearance ─────────────────────────
  gender: 0,
  race: 0,
  body: 0,
  dominant: 0,
  hips: 0,
  butt: 0,
  tallness: 0,
  skinType: 0,
  tail: 0,
  ears: 0,
  hair: 0,
  hairLength: 0,
  hairColor: 0,
  legType: 0,
  wings: 0,
  faceType: 0,
  skinColor: 0,

  // ── Genitals ──────────────────────────────────
  cockTotal: 0,
  humanCocks: 0,
  horseCocks: 0,
  wolfCocks: 0,
  catCocks: 0,
  lizardCocks: 0,
  rabbitCocks: 0,
  cockSize: 0,
  cockMoist: 0,
  balls: 0,
  ballSize: 0,
  showBalls: true,
  knot: false,
  bugCocks: 0,

  // ── Breasts ───────────────────────────────────
  breastSize: 0,
  boobTotal: 0,
  nippleSize: 1,
  udders: false,
  udderSize: 0,
  teatSize: 0,
  clitSize: 0,
  vagTotal: 0,
  vagSize: 0,
  vagMoist: 0,
  vulvaSize: 0,
  nipType: 0,

  // ── Equipment ─────────────────────────────────
  attireTop: 1,
  attireBot: 2,
  weapon: 10,

  // ── Statuses ──────────────────────────────────
  pregArray: [] as any[],
  pregStatus: 0,
  pregnancyTime: 0,
  pregRate: 1,
  eggLaying: 0,
  eggMaxTime: 0,
  eggTime: 0,
  eggRate: 0,
  exhaustion: 0,
  exhaustionPenalty: 0,
  milkEngorgement: 0,
  milkEngorgementLevel: 0,
  udderEngorgement: 0,
  udderEngorgementLevel: 0,
  heat: 0,
  heatTime: 0,
  heatMaxTime: 0,
  lactation: 0,
  udderLactation: 0,
  nipplePlay: 0,
  udderPlay: 0,
  blueBalls: 0,
  teatPump: 0,
  nipPump: 0,
  cockPump: 0,
  clitPump: 0,
  vulvaPump: 0,
  masoPot: 0,
  sMasoPot: 0,
  babyFree: 0,
  charmTime: 0,
  pheromone: 0,
  eggceleratorTime: 0,
  eggceleratorDose: 0,
  bodyOil: 0,
  lustPenalty: 0,
  snuggleBall: false,
  fertileGel: 0,
  eggType: 0,
  milkSuppressant: 0,
  milkSuppressantLact: 0,
  milkSuppressantUdder: 0,
  suppHarness: false,
  fertilityStatueCurse: 0,
  plumpQuats: 0,
  lilaWetStatus: 0,
  cockSnakePreg: 0,
  milkCPoisonNip: 0,
  milkCPoisonUdd: 0,
  cockSnakeVenom: 0,

  // ── Affinities ────────────────────────────────
  humanAffinity: 0,
  horseAffinity: 0,
  wolfAffinity: 0,
  catAffinity: 0,
  cowAffinity: 0,
  lizardAffinity: 0,
  rabbitAffinity: 0,
  fourBoobAffinity: 0,
  mouseAffinity: 0,
  birdAffinity: 0,
  pigAffinity: 0,
  twoBoobAffinity: 0,
  sixBoobAffinity: 0,
  eightBoobAffinity: 0,
  tenBoobAffinity: 0,
  cowTaurAffinity: 0,
  humanTaurAffinity: 0,
  skunkAffinity: 0,
  bugAffinity: 0,

  // ── NPC reputations ───────────────────────────
  lilaRep: 0,
  lilaVulva: 0,
  lilaMilk: 0,
  lilaPreg: -2,
  malonRep: 0,
  malonPreg: 0,
  malonChildren: 0,
  mistressRep: 0,
  jamieRep: 0,
  jamieSize: 4,
  jamieChildren: 0,
  silRep: 0,
  silPreg: 0,
  silRate: 0,
  silLay: 10,
  silTied: false,
  silGrowthTime: 0,
  lilaUB: false,
  dairyFarmBrand: false,
  jamieRep1: 0,
  jamieRep2: 0,
  jamieRep3: 0,
  lilaWetness: 0,
  jamieButt: false,
  jamieBreasts: false,
  jamieHair: false,

  // ── Travelers ─────────────────────────────────
  travArray: [] as any[],

  // ── Discoveries ───────────────────────────────
  foundSoftlik: false,
  foundFirmshaft: false,
  foundTieden: false,
  foundSizCalit: false,
  foundOviasis: false,
  foundValley: false,
  foundSanctuary: false,
  defeatedMinotaur: false,
  defeatedFreakyGirl: false,
  defeatedSuccubus: false,
  firstExplore: false,

  // ── Alchemy knowledge: Simple ─────────────────
  knowLustDraft: false,
  knowRejuvPot: false,
  knowExpPreg: false,
  knowBallSwell: false,
  knowMaleEnhance: false,

  // ── Alchemy knowledge: Complex ────────────────
  knowSLustDraft: false,
  knowSRejuvPot: false,
  knowSExpPreg: false,
  knowSBallSwell: false,
  knowBabyFree: false,
  knowPotPot: false,
  knowGenSwap: false,
  knowMasoPot: false,
  knowMilkSuppress: false,

  // ── Alchemy knowledge: Advanced ───────────────
  knowSGenSwap: false,
  knowSMasoPot: false,
  knowSBabyFree: false,
  knowSPotPot: false,
  knowPussJuice: false,
  knowPheromone: false,
  knowBazoomba: false,

  // ── Class levels ──────────────────────────────
  babyFactLevel: 0,
  bodyBuildLevel: 0,
  hyperHappyLevel: 0,
  alchemistLevel: 0,
  fetishMasterLevel: 0,
  milkMaidLevel: 0,
  shapeshiftyLevel: 0,
  shapeshiftyFirst: '',
  shapeshiftySecond: '',

  // ── Major fetishes ────────────────────────────
  maleFetish: 1,
  femaleFetish: 1,
  hermFetish: 1,
  narcissistFetish: 1,
  dependentFetish: 1,

  // ── Moderate fetishes ─────────────────────────
  dominantFetish: 1,
  submissiveFetish: 1,
  lboobFetish: 1,
  sboobFetish: 1,
  furryFetish: 1,
  scalyFetish: 1,
  smoothyFetish: 1,

  // ── Minor fetishes ────────────────────────────
  pregnancyFetish: 1,
  bestialityFetish: 1,
  milkFetish: 1,
  sizeFetish: 1,
  unbirthingFetish: 1,
  ovipositionFetish: 1,
  toyFetish: 1,
  hyperFetish: 1,

  // ── Daycare / Children ───────────────────────
  currentDayCare: 0,
  humanChildren: 0,
  equanChildren: 0,
  lupanChildren: 0,
  felinChildren: 0,
  cowChildren: 0,
  lizanEggs: 0,
  lizanChildren: 0,
  bunnionChildren: 0,
  wolfPupChildren: 0,
  miceChildren: 0,
  birdEggs: 0,
  birdChildren: 0,
  pigChildren: 0,
  calfChildren: 0,
  bugEggs: 0,
  bugChildren: 0,
  skunkChildren: 0,
  minotaurChildren: 0,
  freakyGirlChildren: 0,

  // ── Inventory ─────────────────────────────────
  bagPage: 1,
  bagArray: [] as number[],
  bagStackArray: [] as number[],
  stashArray: [] as number[],
  stashStackArray: [] as number[],

  // ── Callback: the current button listener ─────
  // Replaces AS3's `var doListen:Function`
  doListen: (() => {}) as () => void,
}

/** Shorthand to reset buttonChoice to 0 */
export function bc(): void { gs.buttonChoice = 0 }
